import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Continuity",
  description:
    "Autonomous integration reliability — monitor provider changes, prove impact, deliver validated migrations.",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-neutral-50 text-neutral-900 antialiased dark:bg-neutral-950 dark:text-neutral-100">
        <div className="mx-auto flex min-h-screen max-w-6xl flex-col px-6">
          <header className="flex items-center justify-between border-b border-neutral-200 py-5 dark:border-neutral-800">
            <Link
              href="/"
              className="text-sm font-semibold tracking-tight focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-500"
            >
              Continuity
            </Link>
            <nav aria-label="Main" className="flex gap-4 text-xs">
              <Link
                href="/projects"
                className="text-neutral-600 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-neutral-100"
              >
                Projects
              </Link>
              <Link
                href="/approvals"
                className="text-neutral-600 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-neutral-100"
              >
                Approvals
              </Link>
            </nav>
          </header>
          <main className="flex-1 py-10">{children}</main>
          <footer className="border-t border-neutral-200 py-5 text-xs text-neutral-500 dark:border-neutral-800 dark:text-neutral-400">
            Every figure shown is read from Continuity&rsquo;s own records of what
            ran. Nothing here is generated by a language model.
          </footer>
        </div>
      </body>
    </html>
  );
}
