"""Deterministic repository index.

This is the module that makes `02_ARCHITECTURE.md` §4's central promise real:
**a repository is never dumped into a model.** Everything a model later sees is
selected from this index by `backend/repository/retrieval.py`, under a byte
budget, secret-filtered.

Pipeline:

    source → exclusion filter → classification → manifest + AST analysis → index

No model is involved at any step. Every fact the index holds is `CONFIRMED` and
carries a file path and, where applicable, a line span — which is what lets the
UI cite evidence for every claim it makes later.

Ordering is not incidental. Exclusion runs before classification, which runs
before reading, so a `.env` is skipped by name and its bytes never enter the
process.
"""

from __future__ import annotations

import json
from collections.abc import Iterator
from dataclasses import asdict, dataclass, field
from enum import StrEnum
from typing import Any

from backend.observability.logging import get_logger
from backend.repository.analyzers.manifests import (
    LOCKFILE_FILENAMES,
    MANIFEST_FILENAMES,
    Dependency,
    parse_manifest,
)
from backend.repository.analyzers.python_analyzer import analyze_python
from backend.repository.analyzers.typescript_analyzer import analyze_typescript
from backend.repository.source import RepositoryFile, RepositorySource
from backend.security.secret_filter import classify_path, is_secret_path

logger = get_logger(__name__)

#: Read limit. Larger files are recorded by name and size only — checked with
#: `stat`, so an oversized file is never read to discover that it is oversized.
MAX_INDEXED_FILE_BYTES = 400_000


class FileKind(StrEnum):
    SOURCE = "source"
    TEST = "test"
    CONFIG = "config"
    MANIFEST = "manifest"
    LOCKFILE = "lockfile"
    DOC = "doc"
    GENERATED = "generated"
    OTHER = "other"


class Language(StrEnum):
    PYTHON = "python"
    TYPESCRIPT = "typescript"
    JAVASCRIPT = "javascript"
    JSON = "json"
    YAML = "yaml"
    TOML = "toml"
    MARKDOWN = "markdown"
    OTHER = "other"


_LANGUAGE_BY_SUFFIX = {
    ".py": Language.PYTHON,
    ".pyi": Language.PYTHON,
    ".ts": Language.TYPESCRIPT,
    ".tsx": Language.TYPESCRIPT,
    ".mts": Language.TYPESCRIPT,
    ".cts": Language.TYPESCRIPT,
    ".js": Language.JAVASCRIPT,
    ".jsx": Language.JAVASCRIPT,
    ".mjs": Language.JAVASCRIPT,
    ".cjs": Language.JAVASCRIPT,
    ".json": Language.JSON,
    ".yaml": Language.YAML,
    ".yml": Language.YAML,
    ".toml": Language.TOML,
    ".md": Language.MARKDOWN,
}

_CONFIG_SUFFIXES = frozenset({".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf"})

_TEST_MARKERS = ("test_", "_test.", ".test.", ".spec.")
_TEST_DIRECTORIES = frozenset({"tests", "test", "__tests__", "spec"})

_GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "code generated by",
)

#: A framework is claimed only when its own import appears — not when a
#: dependency merely lists it, which would misreport a transitive package.
_FRAMEWORK_IMPORTS = {
    "fastapi": "fastapi",
    "flask": "flask",
    "django": "django",
    "starlette": "starlette",
    "express": "express",
    "next": "nextjs",
    "react": "react",
    "vue": "vue",
    "svelte": "svelte",
}


@dataclass(frozen=True, slots=True)
class IndexedSymbol:
    qualified_name: str
    kind: str
    line_start: int
    line_end: int
    is_route: bool = False
    http_method: str | None = None
    route_path: str | None = None


@dataclass(frozen=True, slots=True)
class IndexedStringLiteral:
    value: str
    line: int
    enclosing_symbol: str | None


@dataclass(frozen=True, slots=True)
class IndexedCallSite:
    callee: str
    line: int
    enclosing_symbol: str | None
    arguments_preview: tuple[str, ...] = ()


@dataclass(slots=True)
class IndexedFile:
    path: str
    kind: FileKind
    language: Language
    size_bytes: int
    line_count: int = 0
    content_hash: str = ""
    symbols: list[IndexedSymbol] = field(default_factory=list)
    call_sites: list[IndexedCallSite] = field(default_factory=list)
    imports: list[str] = field(default_factory=list)
    string_literals: list[IndexedStringLiteral] = field(default_factory=list)
    http_clients: set[str] = field(default_factory=set)
    webhook_symbols: set[str] = field(default_factory=set)
    #: True when facts came from regex rather than a real parse (TS/JS).
    heuristic: bool = False
    read_skipped: str | None = None
    parse_error: str | None = None


@dataclass(slots=True)
class ExcludedPath:
    path: str
    reason: str
    is_secret: bool


@dataclass(slots=True)
class RepositoryIndex:
    """The complete deterministic picture of one repository."""

    source_identifier: str
    files: dict[str, IndexedFile] = field(default_factory=dict)
    dependencies: list[Dependency] = field(default_factory=list)
    excluded: list[ExcludedPath] = field(default_factory=list)
    frameworks: set[str] = field(default_factory=set)
    languages: set[Language] = field(default_factory=set)
    ecosystems: set[str] = field(default_factory=set)

    # --- queries the mapper and retrieval rely on ---

    @property
    def secret_paths_excluded(self) -> int:
        """How many files were skipped *because they held secrets*.

        Surfaced separately from ordinary noise: it is a security control doing
        its job, and worth showing on the scan summary.
        """
        return sum(1 for entry in self.excluded if entry.is_secret)

    def source_files(self) -> Iterator[IndexedFile]:
        return (f for f in self.files.values() if f.kind in (FileKind.SOURCE, FileKind.TEST))

    def files_importing(self, module_root: str) -> list[IndexedFile]:
        return [
            f
            for f in self.files.values()
            if any(imp == module_root or imp.startswith(f"{module_root}.") for imp in f.imports)
        ]

    def call_sites_matching(self, needle: str) -> list[tuple[IndexedFile, IndexedCallSite]]:
        needle_lower = needle.lower()
        found: list[tuple[IndexedFile, IndexedCallSite]] = []
        for file in self.files.values():
            for call in file.call_sites:
                haystack = f"{call.callee} {' '.join(call.arguments_preview)}".lower()
                if needle_lower in haystack:
                    found.append((file, call))
        return found

    def webhook_handlers(self) -> list[tuple[IndexedFile, str]]:
        return [(f, symbol) for f in self.files.values() for symbol in sorted(f.webhook_symbols)]

    def routes(self) -> list[tuple[IndexedFile, IndexedSymbol]]:
        return [(f, s) for f in self.files.values() for s in f.symbols if s.is_route]

    def test_files(self) -> list[IndexedFile]:
        return [f for f in self.files.values() if f.kind is FileKind.TEST]

    def summary(self) -> dict[str, Any]:
        """Compact, JSON-safe scan summary. Contains no file content."""
        return {
            "source": self.source_identifier,
            "files_indexed": len(self.files),
            "files_excluded": len(self.excluded),
            "secret_paths_excluded": self.secret_paths_excluded,
            "languages": sorted(language.value for language in self.languages),
            "frameworks": sorted(self.frameworks),
            "ecosystems": sorted(self.ecosystems),
            "dependencies": len(self.dependencies),
            "symbols": sum(len(f.symbols) for f in self.files.values()),
            "call_sites": sum(len(f.call_sites) for f in self.files.values()),
            "routes": len(self.routes()),
            "webhook_handlers": len(self.webhook_handlers()),
            "tests": len(self.test_files()),
        }


def classify_file(path: str, size_bytes: int) -> tuple[FileKind, Language]:
    """Decide what a file is, from its path alone. No content is read."""
    lowered = path.lower()
    name = lowered.rsplit("/", 1)[-1]
    suffix = f".{name.rsplit('.', 1)[-1]}" if "." in name else ""
    language = _LANGUAGE_BY_SUFFIX.get(suffix, Language.OTHER)
    segments = set(lowered.split("/")[:-1])

    if name in LOCKFILE_FILENAMES:
        return FileKind.LOCKFILE, language
    if name in MANIFEST_FILENAMES:
        return FileKind.MANIFEST, language
    if any(marker in name for marker in _TEST_MARKERS) or segments & _TEST_DIRECTORIES:
        return FileKind.TEST, language
    if language is Language.MARKDOWN or name in ("readme", "license", "changelog"):
        return FileKind.DOC, language
    if suffix in _CONFIG_SUFFIXES:
        return FileKind.CONFIG, language
    if language in (
        Language.PYTHON,
        Language.TYPESCRIPT,
        Language.JAVASCRIPT,
    ):
        return FileKind.SOURCE, language

    return FileKind.OTHER, language


def _looks_generated(content: str) -> bool:
    """Generated files are indexed but never migrated — editing one is futile."""
    head = content[:2000].lower()
    return any(marker in head for marker in _GENERATED_MARKERS)


def build_index(
    source: RepositorySource, *, max_file_bytes: int = MAX_INDEXED_FILE_BYTES
) -> RepositoryIndex:
    """Walk a repository and produce its deterministic index."""
    import hashlib

    index = RepositoryIndex(source_identifier=source.identifier)

    for entry in source.list_files():
        _index_one(index, source, entry, max_file_bytes, hashlib)

    # Paths the source pruned during its walk. Merged here so the summary
    # counts every exclusion, not only those the indexer saw for itself.
    for path, reason in getattr(source, "skipped_paths", list)():
        index.excluded.append(
            ExcludedPath(path=path, reason=reason, is_secret=is_secret_path(path))
        )
    index.excluded.sort(key=lambda entry: entry.path)

    logger.info("continuity.repository_indexed", extra=index.summary())
    return index


def _index_one(
    index: RepositoryIndex,
    source: RepositorySource,
    entry: RepositoryFile,
    max_file_bytes: int,
    hashlib_module: Any,
) -> None:
    verdict = classify_path(entry.path)
    if verdict.excluded:
        index.excluded.append(
            ExcludedPath(
                path=entry.path,
                reason=verdict.detail or verdict.reason.value,
                is_secret=is_secret_path(entry.path),
            )
        )
        return

    kind, language = classify_file(entry.path, entry.size_bytes)
    indexed = IndexedFile(
        path=entry.path, kind=kind, language=language, size_bytes=entry.size_bytes
    )
    index.files[entry.path] = indexed
    if language is not Language.OTHER:
        index.languages.add(language)

    # Size is checked before reading, so an oversized file costs one stat.
    if entry.size_bytes > max_file_bytes:
        indexed.read_skipped = f"exceeds {max_file_bytes} bytes"
        return

    try:
        content = source.read_file(entry.path)
    except Exception as exc:
        indexed.read_skipped = f"unreadable: {type(exc).__name__}"
        return

    if not content:
        return

    indexed.line_count = content.count("\n") + 1
    indexed.content_hash = hashlib_module.sha256(content.encode("utf-8")).hexdigest()[:16]

    if _looks_generated(content):
        indexed.kind = FileKind.GENERATED
        return

    if kind in (FileKind.MANIFEST,):
        manifest = parse_manifest(entry.path, content)
        index.dependencies.extend(manifest.dependencies)
        if manifest.ecosystem:
            index.ecosystems.add(manifest.ecosystem)
        if manifest.parse_error:
            indexed.parse_error = manifest.parse_error
        return

    if language is Language.PYTHON:
        _apply_python(index, indexed, content)
    elif language in (Language.TYPESCRIPT, Language.JAVASCRIPT):
        _apply_typescript(index, indexed, content)


def _apply_python(index: RepositoryIndex, indexed: IndexedFile, content: str) -> None:
    analysis = analyze_python(content)
    if analysis.parse_error:
        indexed.parse_error = analysis.parse_error
        return

    indexed.symbols = [
        IndexedSymbol(
            qualified_name=s.qualified_name,
            kind=s.kind,
            line_start=s.line_start,
            line_end=s.line_end,
            is_route=s.is_route,
            http_method=s.http_method,
            route_path=s.route_path,
        )
        for s in analysis.symbols
    ]
    indexed.call_sites = [
        IndexedCallSite(
            callee=c.callee,
            line=c.line,
            enclosing_symbol=c.enclosing_symbol,
            arguments_preview=c.arguments_preview,
        )
        for c in analysis.calls
    ]
    indexed.imports = sorted({record.module for record in analysis.imports if record.module})
    indexed.string_literals = [
        IndexedStringLiteral(
            value=literal.value, line=literal.line, enclosing_symbol=literal.enclosing_symbol
        )
        for literal in analysis.string_literals
    ]
    indexed.http_clients = set(analysis.http_client_modules)
    indexed.webhook_symbols = set(analysis.webhook_symbols)

    for module in indexed.imports:
        framework = _FRAMEWORK_IMPORTS.get(module.split(".")[0])
        if framework:
            index.frameworks.add(framework)


def _apply_typescript(index: RepositoryIndex, indexed: IndexedFile, content: str) -> None:
    analysis = analyze_typescript(content)
    indexed.heuristic = True
    indexed.symbols = [
        IndexedSymbol(
            qualified_name=s.name, kind=s.kind, line_start=s.line_start, line_end=s.line_start
        )
        for s in analysis.symbols
    ]
    indexed.call_sites = [
        IndexedCallSite(
            callee=c.callee, line=c.line, enclosing_symbol=None, arguments_preview=(c.target,)
        )
        for c in analysis.calls
    ]
    indexed.imports = sorted({record.module for record in analysis.imports})
    indexed.http_clients = set(analysis.http_client_packages)

    for module in indexed.imports:
        framework = _FRAMEWORK_IMPORTS.get(module.split("/")[0])
        if framework:
            index.frameworks.add(framework)


def index_to_snapshot(index: RepositoryIndex) -> dict[str, Any]:
    """Stable, JSON-native form used by the snapshot test.

    Sets become sorted lists and enums become their values, so two runs over the
    same tree produce byte-equal output and a stored snapshot compares equal
    after a JSON round-trip. A snapshot that reordered itself, or that differed
    only by `FileKind.SOURCE` vs `"source"`, would be untestable.
    """
    payload = {
        "summary": index.summary(),
        "files": {
            path: {
                **{
                    key: value
                    for key, value in asdict(file).items()
                    if key
                    not in (
                        "symbols",
                        "call_sites",
                        "http_clients",
                        "webhook_symbols",
                        "string_literals",
                    )
                },
                "http_clients": sorted(file.http_clients),
                "webhook_symbols": sorted(file.webhook_symbols),
                "symbols": [asdict(symbol) for symbol in file.symbols],
                "call_sites": [asdict(call) for call in file.call_sites],
                "string_literals": [asdict(literal) for literal in file.string_literals],
            }
            for path, file in sorted(index.files.items())
        },
        "dependencies": sorted(
            (asdict(dependency) for dependency in index.dependencies),
            key=lambda item: (item["manifest_path"], item["name"]),
        ),
        "excluded": sorted(
            (asdict(entry) for entry in index.excluded), key=lambda item: item["path"]
        ),
    }
    # Round-trip through JSON so enums, sets, and tuples land in exactly the
    # form a stored snapshot will be read back as.
    return json.loads(json.dumps(payload, sort_keys=True, default=str))  # type: ignore[no-any-return]
