"""baseline schema

Revision ID: 3e8cdd6bfd68
Revises:
Create Date: 2026-09-10 08:11:24.697535

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e8cdd6bfd68'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('old_version', sa.String(length=64), nullable=False),
    sa.Column('new_version', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=1024), nullable=False),
    sa.Column('old_contract', sa.JSON(), nullable=True),
    sa.Column('new_contract', sa.JSON(), nullable=True),
    sa.Column('breaking', sa.Boolean(), nullable=False),
    sa.Column('security_relevant', sa.Boolean(), nullable=False),
    sa.Column('authentication_relevant', sa.Boolean(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'old_version', 'new_version', 'change_type', 'resource', name='uq_change_event_dedup')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_events_breaking'), ['breaking'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_provider_id'), ['provider_id'], unique=False)

    op.create_table('provider_specs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('parsed_ok', sa.Boolean(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_specs_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_provider_specs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_specs_version'), ['version'], unique=False)

    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('adapter_name', sa.String(length=128), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_provider_id'), ['provider_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_google_subject'), ['google_subject'], unique=True)

    op.create_table('github_installations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_installations_installation_id'), ['installation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_github_installations_user_id'), ['user_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sa.Uuid(), nullable=True),
    sa.Column('github_repo_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('local_path', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['github_installations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'name', name='uq_repository_owner_name')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_github_repo_id'), ['github_repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_installation_id'), ['installation_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('current_graph_version', sa.Integer(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'graph_version', 'kind', 'key', name='uq_graph_node_identity')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_graph_node_lookup', ['project_id', 'graph_version', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_nodes_graph_version'), ['graph_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_nodes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_nodes_project_id'), ['project_id'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('sdk_package', sa.String(length=255), nullable=True),
    sa.Column('detected_api_version', sa.String(length=64), nullable=True),
    sa.Column('auth_mechanism', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'provider_id', name='uq_integration_project_provider')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_provider_id'), ['provider_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('migration_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('change_event_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('from_version', sa.String(length=64), nullable=False),
    sa.Column('to_version', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=255), nullable=True),
    sa.Column('source_commit', sa.String(length=64), nullable=True),
    sa.Column('target_branch', sa.String(length=255), nullable=True),
    sa.Column('rehearsal', sa.JSON(), nullable=True),
    sa.Column('evidence_report', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_runs_change_event_id'), ['change_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_migration_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_migration_runs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_migration_runs_state'), ['state'], unique=False)

    op.create_table('provider_baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('spec_id', sa.Uuid(), nullable=True),
    sa.Column('established_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['provider_specs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'provider_id', name='uq_baseline_project_provider')
    )
    with op.batch_alter_table('provider_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_baselines_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_baselines_provider_id'), ['provider_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('migration_run_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_migration_run_id'), ['migration_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_state'), ['state'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('migration_run_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=128), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_action', sa.JSON(), nullable=False),
    sa.Column('agent_recommendation', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_migration_run_id'), ['migration_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_trigger'), ['trigger'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_version', 'kind', 'source_node_id', 'target_node_id', name='uq_graph_edge')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index('ix_graph_edge_traverse', ['project_id', 'graph_version', 'source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_graph_version'), ['graph_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_source_node_id'), ['source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_target_node_id'), ['target_node_id'], unique=False)

    op.create_table('migration_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('migration_run_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('plan_summary', sa.Text(), nullable=True),
    sa.Column('files_changed', sa.JSON(), nullable=True),
    sa.Column('patch_diff', sa.Text(), nullable=True),
    sa.Column('commands_executed', sa.JSON(), nullable=True),
    sa.Column('tests_executed', sa.JSON(), nullable=True),
    sa.Column('failure_evidence', sa.JSON(), nullable=True),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('migration_run_id', 'attempt_number', name='uq_attempt_number')
    )
    with op.batch_alter_table('migration_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_attempts_migration_run_id'), ['migration_run_id'], unique=False)

    op.create_table('pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('migration_run_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'number', name='uq_pull_request_repo_number')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_requests_migration_run_id'), ['migration_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_state'), ['state'], unique=False)

    op.create_table('security_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('migration_run_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(length=16), nullable=False),
    sa.Column('policy_decision', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_findings_migration_run_id'), ['migration_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_findings_severity'), ['severity'], unique=False)

    op.create_table('state_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('migration_run_id', sa.Uuid(), nullable=True),
    sa.Column('from_state', sa.String(length=64), nullable=False),
    sa.Column('to_state', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_transitions_migration_run_id'), ['migration_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_transitions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_transitions_project_id'), ['project_id'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('migration_run_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_project_id'), ['project_id'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'sequence', name='uq_agent_step_seq')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_agent_run_id'), ['agent_run_id'], unique=False)

    op.create_table('test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('migration_run_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('suite', sa.String(length=128), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('failing_test_ids', sa.JSON(), nullable=True),
    sa.Column('raw_output_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['migration_attempts.id'], ),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_migration_run_id'), ['migration_run_id'], unique=False)

    op.create_table('tool_invocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('policy_decision', sa.String(length=16), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_invocations_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_invocations_policy_decision'), ['policy_decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_invocations_tool_name'), ['tool_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_invocations_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_invocations_policy_decision'))
        batch_op.drop_index(batch_op.f('ix_tool_invocations_agent_run_id'))

    op.drop_table('tool_invocations')
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_migration_run_id'))

    op.drop_table('test_results')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_agent_run_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_activity_events_kind'))

    op.drop_table('activity_events')
    with op.batch_alter_table('state_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_transitions_project_id'))
        batch_op.drop_index(batch_op.f('ix_state_transitions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_state_transitions_migration_run_id'))

    op.drop_table('state_transitions')
    with op.batch_alter_table('security_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_security_findings_migration_run_id'))
        batch_op.drop_index(batch_op.f('ix_security_findings_category'))

    op.drop_table('security_findings')
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_requests_state'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_repository_id'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_number'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_migration_run_id'))

    op.drop_table('pull_requests')
    with op.batch_alter_table('migration_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_attempts_migration_run_id'))

    op.drop_table('migration_attempts')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_target_node_id'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_source_node_id'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_project_id'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_kind'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_graph_version'))
        batch_op.drop_index('ix_graph_edge_traverse')

    op.drop_table('graph_edges')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_trigger'))
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_project_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_migration_run_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_state'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_role'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_migration_run_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('provider_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_baselines_provider_id'))
        batch_op.drop_index(batch_op.f('ix_provider_baselines_project_id'))

    op.drop_table('provider_baselines')
    with op.batch_alter_table('migration_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_runs_state'))
        batch_op.drop_index(batch_op.f('ix_migration_runs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_migration_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_migration_runs_change_event_id'))

    op.drop_table('migration_runs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_provider_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_project_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_project_id'))
        batch_op.drop_index(batch_op.f('ix_graph_nodes_kind'))
        batch_op.drop_index(batch_op.f('ix_graph_nodes_graph_version'))
        batch_op.drop_index('ix_graph_node_lookup')

    op.drop_table('graph_nodes')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_kind'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor'))

    op.drop_table('audit_events')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_state'))
        batch_op.drop_index(batch_op.f('ix_projects_repository_id'))

    op.drop_table('projects')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_installation_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_github_repo_id'))

    op.drop_table('repositories')
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_installations_user_id'))
        batch_op.drop_index(batch_op.f('ix_github_installations_installation_id'))

    op.drop_table('github_installations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_subject'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_provider_id'))

    op.drop_table('providers')
    with op.batch_alter_table('provider_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_specs_version'))
        batch_op.drop_index(batch_op.f('ix_provider_specs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_provider_specs_content_hash'))

    op.drop_table('provider_specs')
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_events_provider_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_detected_at'))
        batch_op.drop_index(batch_op.f('ix_change_events_change_type'))
        batch_op.drop_index(batch_op.f('ix_change_events_breaking'))

    op.drop_table('change_events')
    # ### end Alembic commands ###
