"""security findings belong to an attempt

Revision ID: a39d335d7f8a
Revises: 7ddf8497d129
Create Date: 2026-09-11 22:40:21.450495

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a39d335d7f8a'
down_revision: str | Sequence[str] | None = '7ddf8497d129'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_findings', schema=None) as batch_op:
        batch_op.drop_column('attempt_number')

    # ### end Alembic commands ###
